# Generated by Django 5.1.7 on 2025-04-10 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_city"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tg_chat_id",
            field=models.CharField(
                blank=True,
                help_text="Введите Chat-ID Telegram",
                max_length=50,
                null=True,
                verbose_name="Chat-ID Telegram",
            ),
        ),
    ]
